learning/basicapp/urls.py
from django.conf.urls import url
from basicapp import views


app_name = 'basicapp'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user_login'),
    
]

learning/learning/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basicapp import views 

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    url(r'^basicapp/', include('basicapp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/$', views.special, name='special'),
]
    

learning/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to = 'profile_pic', blank= True)

    def __str__(self):
        return self.user.username

learning/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning/basicapp/views.py
import imp
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse


# Create your views here.
def index(request):
    return render(request, 'basicapp/index.html')

@login_required
def special(request):
    return HttpResponse("you are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    
    registered = False
    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basicapp/registration.html', {'user_form':user_form, 'profile_form':profile_form,
    'registered':registered})


def user_login(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account Not Active")

        else:
            print("Someone tried to login and failed")
            print("username:{} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'basicapp/login.html', {})

learning/templates/basicapp/base.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
    </head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <body>
        
        <nav class = 'navbar navbar-default navbar-static-top'>
            <div>
                <ul>
                    <li><a class = "navbar-brand" href="{% url 'index' %}">Django</a></li>\
                    <li><a class = "navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class = "navbar-link" href="{% url 'basicapp:register' %}">Register</a></li>
                    
                    {% if user.is_authenticated %}
                    <li><a class = "navbar-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class = "navbar-link" href="{% url 'basicapp:user_login' %}">Login</a></li>
                    {% endif %}

                </ul>
            </div>

        </nav>
        {% block body_block %}
        {% endblock %}

    </body>
</html>

learning/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django level 5</h1>
</div>
{% endblock %}

learning/templates/basicapp/login.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basicapp:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">UserName</label>
        <input type="text" name = "username" placeholder="Enter User Name">

        <label for="password">Password</label>
        <input type="password" name = "password">
        <input type="submit" name="" value="Login">
    </form>
</div>

{% endblock %}

learning/templates/basicapp/registration.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>Thankyou for registering</h1>
    {% else %}
    <h1>Register here</h1>
    <h3>Fill out the forn</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p}}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>

    {% endif %}
</div>

{% endblock %}